[tools]
# php = "8.3.24"

[env]
SWEETDATE_BASE_URL = "http://localhost:4008"
SWEETDATE_APP_ID = "app_f4578a53-9f6c-469d-b241-387b66de033c"
SWEETDATE_SK_B64URL = "wgyryd1kThzKRC3UnZIZqnzQI0WUkukchW-BgH4PQvU"
SWEETDATE_TIMEOUT_MS = "10000"

[tasks]



